# Numpy and Linear Algebra

## Where do numpy arrays show up in ML?

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.DataFrame([[0,2,1], [2,3,4], [8,5,6]], columns=["x1", "x2", "y"])
df

x1  x2  y
0   0   2  1
1   2   3  4
2   8   5  6

In [4]:
df.values

array([[0, 2, 1],
       [2, 3, 4],
       [8, 5, 6]])

In [5]:
type(df.values)

numpy.ndarray

In [6]:
model = LinearRegression()
model.fit(df[["x1", "x2"]], df["y"])

LinearRegression()

In [9]:
model.coef_

array([-2.,  7.])

In [12]:
model.intercept_

-12.999999999999988

In [13]:
model.predict(df[["x1", "x2"]])

array([1., 4., 6.])

In [15]:
df[["x1", "x2"]].values @ model.coef_ + model.intercept_ # "@" is dot product -- to be learned soon!

array([1., 4., 6.])

## How to create numpy arrays from scratch?

In [16]:
import numpy as np

In [17]:
np.array([7,8,9])

array([7, 8, 9])

In [18]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#list(range(START, END, STEP))

In [22]:
list(range(10, 20, 2))

[10, 12, 14, 16, 18]

In [25]:
#list(range(0, 1, 0.2)) # Python range only works with int

In [26]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

## How to slice numpy arrays?

In [28]:
a = [7,8,9,10]
b = a[2:] # slicing a list creates an independent list
b

[9, 10]

In [29]:
b[0] = 100
b

[100, 10]

In [30]:
a

[7, 8, 9, 10]

In [31]:
a = np.array([7,8,9,10])
b = a[2:] # slicing an arrays shares underlying values
b

array([ 9, 10])

In [32]:
b[0] = 100
b

array([100,  10])

In [33]:
a

array([  7,   8, 100,  10])

## Using Multi-Dimensional Arrays

## Images as Tensors

In [ ]:
# pip3 install Pillow

## Vector Multiplication: Overview

### Elementwise Multiplication

$\begin{bmatrix}
1 \\ 2 \\ 3
\end{bmatrix}
*
\begin{bmatrix}
4 \\ 5 \\ 6
\end{bmatrix}$

$\begin{bmatrix}
1 \\ 2 \\ 3
\end{bmatrix}
*
\begin{bmatrix}
4 & 5 & 6
\end{bmatrix}$

### Dot Product

$\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
\cdot
\begin{bmatrix}
4 \\ 5 \\ 6
\end{bmatrix}$

$\begin{bmatrix}
1 \\ 2 \\ 3
\end{bmatrix}
\cdot
\begin{bmatrix}
4 & 5 & 6
\end{bmatrix}$

## Transpose

## Broadcast

## Dot Product