# Numpy and Linear Algebra

## Where do numpy arrays show up in ML?

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.DataFrame([[0,2,1], [2,3,4], [8,5,6]], columns=["x1", "x2", "y"])
df

x1  x2  y
0   0   2  1
1   2   3  4
2   8   5  6

In [4]:
print(type(df.values))
df.values

<class 'numpy.ndarray'>


array([[0, 2, 1],
       [2, 3, 4],
       [8, 5, 6]])

In [6]:
lr = LinearRegression()
lr.fit(df[["x1", "x2"]], df["y"])
lr.coef_

array([-2.,  7.])

In [8]:
lr.predict(df[["x1", "x2"]])

array([1., 4., 6.])

In [10]:
# "@" is the dot product -- will learn more soon
df[["x1", "x2"]].values @ lr.coef_ + lr.intercept_

array([1., 4., 6.])

## How to create numpy arrays from scratch?

In [13]:
import numpy as np

np.array([7,8,9])

array([7, 8, 9])

In [14]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# list(range(START, END, STEP))

In [18]:
list(range(10, 20, 2))

[10, 12, 14, 16, 18]

In [20]:
# doesn't work in Python -- need ints
# list(range(0, 1, 0.2))

In [21]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

## How to slice numpy arrays?

In [25]:
a = [7,8,9,10]
b = a[1 :  : 2] # slicing a list creates an independent list
b

[8, 10]

In [23]:
b[1] = 100
b

[8, 100]

In [24]:
a

[7, 8, 9, 10]

In [26]:
a = np.array([7,8,9,10])
b = a[1 :  : 2] # numpy slices still share with the originals
b

array([ 8, 10])

In [27]:
b[1] = 100
b

array([  8, 100])

In [28]:
a

array([  7,   8,   9, 100])

## Using Multi-Dimensional Arrays

In [29]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [30]:
len(a)

3

In [32]:
a.shape # 1D, size 3 (vector)

(3,)

In [38]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
len(b)

2

In [35]:
b.shape

(2, 3)

In [40]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
b.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [43]:
#b.reshape(3,3)

In [44]:
b.reshape(3,-1) # -1 means whatever size is necessary

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
b.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [46]:
b.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [47]:
b.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [48]:
np.ones(80).reshape(-1,8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# scalar=0D, vector=1D, matrix=2D
# tensor: array of any number of dimensions

## Images as Tensors

## Vector Multiplication: Overview

### Elementwise Multiplication

$\begin{bmatrix}
1 \\ 2 \\ 3
\end{bmatrix}
*
\begin{bmatrix}
4 \\ 5 \\ 6
\end{bmatrix}$

$\begin{bmatrix}
1 \\ 2 \\ 3
\end{bmatrix}
*
\begin{bmatrix}
4 & 5 & 6
\end{bmatrix}$

### Dot Product

$\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
\cdot
\begin{bmatrix}
4 \\ 5 \\ 6
\end{bmatrix}$

$\begin{bmatrix}
1 \\ 2 \\ 3
\end{bmatrix}
\cdot
\begin{bmatrix}
4 & 5 & 6
\end{bmatrix}$

## Transpose

## Broadcast

## Dot Product